### ISSUE TITLE
Sanity tests failing in community.dns

### ISSUE THREAD

**Issue by dmsimard** [ansible-collections/community.dns#100]
##### SUMMARY
We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)) and found that ``ansible-test sanity --docker`` against community.dns 2.1.0 fails with ansible-core 2.13.0rc1 in ansible 6.0.0a2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
n/a

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.0rc1]
```

##### COLLECTION VERSION

```paste below
2.1.0
```

##### STEPS TO REPRODUCE

```yaml
ansible-test sanity --docker
```

##### EXPECTED RESULTS

Tests are either passing or ignored.

##### ACTUAL RESULTS

```paste below
ERROR: Found 3 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/hosttech_dns_records.py:0:0: deprecation-mismatch: "meta/runtime.yml" and DOCUMENTATION.deprecation do not agree.
ERROR: plugins/modules/hosttech_dns_records.py:0:0: invalid-documentation: DOCUMENTATION.deprecated: required key not provided @ data['deprecated']. Got None
ERROR: plugins/modules/hosttech_dns_records.py:0:0: invalid-documentation: DOCUMENTATION.module: not a valid value for dictionary value @ data['module']. Got 'hosttech_dns_record_sets'
ERROR: The 1 sanity test(s) listed below (out of 43) failed. See error output above for details.
validate-modules
ERROR: Command "podman exec ansible-test-controller-h3Y09sKe /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/community/dns LC_ALL=en_US.UTF-8 /usr/bin/python3.10 /root/ansible/bin/ansible-test sanity --containers '{}' --skip-test pylint --metadata tests/output/.tmp/metadata-apf9lg29.json --truncate 0 --color no --host-path tests/output/.tmp/host-tqxg7wn5" returned exit status 1.
```

**Comment by felixfontein** [comment]
@dmsimard you really want to run the tests on the output of `ansible-galaxy collection install <collection-name>`, not on the extracted tar file. Because this only happens because of https://github.com/ansible-community/antsibull/issues/218.
