### ISSUE TITLE
HETZNER_DNS_TOKEN env_fallback not working

### ISSUE THREAD

**Issue by flortsch** [ansible-collections/community.dns#115]
##### SUMMARY
The hetzner_dns_record module has a required argument called `hetzner_token`. The documentation states that this argument is optional, and the env var `HETZNER_DNS_TOKEN` is used as fallback when this argument is not defined. I see in the file `plugins/module_utils/hetzner/api.py` that there is indeed an `env_fallback` used. However, not defining the argument results in an error: `missing required arguments: hetzner_token`. I think it's because the argument has the `required` flag set to `True`, which should not be the case according to the documentation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.dns.hetzner_dns_record`

##### ANSIBLE VERSION
```
ansible [core 2.13.4]
  config file = /home/flortsch/Projekte/ansible-test/ansible.cfg
  configured module search path = ['/home/flortsch/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/flortsch/Projekte/ansible-test/.galaxy/collections
  executable location = /usr/bin/ansible
  python version = 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /usr/lib/python3.10/site-packages/ansible_collections
Collection    Version
------------- -------
community.dns 2.3.2 
```

##### CONFIGURATION
```
COLLECTIONS_PATHS(/home/flortsch/Projekte/test-ansible/ansible.cfg) = ['/home/flortsch/Projekte/test-ansible/.galaxy/collections']
DEFAULT_HOST_LIST(/home/flortsch/Projekte/test-ansible/ansible.cfg) = ['/home/flortsch/Projekte/test-ansible/inventory']
DEFAULT_ROLES_PATH(/home/flortsch/Projekte/test-ansible/ansible.cfg) = ['/home/flortsch/Projekte/test-ansible/.galaxy/roles', '/home/flortsch/Projekte/test-ansible/roles']
```

##### OS / ENVIRONMENT
Arch Linux (ansible 6.4.0-1)

##### STEPS TO REPRODUCE

Use an example task from the documentation.

```yaml
  tasks:
    - name: set up DNS records
      community.dns.hetzner_dns_record:
        state: present
        zone: example.com
        record: test.example.com
        type: A
        value: 1.1.1.1
```

##### EXPECTED RESULTS

According to the documentation, the task should not fail when env var `HETZNER_DNS_TOKEN` is provided.

##### ACTUAL RESULTS
The task fails with error: `missing required arguments: hetzner_token`.

**Comment by felixfontein** [comment]
> The documentation states that this argument is optional

That is not the case: https://github.com/ansible-collections/community.dns/blob/main/plugins/doc_fragments/hetzner.py#L23
(See also the rendered docs: https://docs.ansible.com/ansible/devel/collections/community/dns/hetzner_dns_record_module.html#parameter-hetzner_token - it has a red 'required'.)

Regarding the environment variable:

From your example it is not clear whether the env var `HETZNER_DNS_TOKEN` is defined on the machine / environment in / on which the module is executed.

**Comment by felixfontein** [comment]
I did test both the `hetzner_dns_zone_info` module and the inventory plugin with the environment variable (without specifying the `hetzner_token` option), and for me it worked.

**Comment by flortsch** [comment]
Okay, the error was on my side - sorry for the inconvenience. The tasks in my setup were executed on the remote host where the env var obviously was not defined. So if one wants to execute the tasks on the remote host, one has to set the `hetzner_token` argument to `'{{ lookup("env", "HETZNER_DNS_TOKEN") }}` or define the envvar via `environment` on the task. Or one just runs the tasks on localhost.

**Comment by felixfontein** [comment]
From a security point of view, if there are no good reasons to run it on the remote host, I would suggest to run it on `localhost` to avoid needing to make the token available to the remote host.

Anyway, closing since this is resolved :)
