### ISSUE TITLE
hetzner_dns_records_inventory, Doc details missing

### ISSUE THREAD

**Issue by nklamann** [ansible-collections/community.dns#130]
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

hetzner_dns_records_inventory
##### ANSIBLE VERSION

```paste below
current as of 20230125
```
parameter `plugin` is not documented, must be set to  `community.dns.hetzner_dns_records`

The required ending of the configuration file name is also not documented, i had to look it up in the source code

**Comment by felixfontein** [comment]
Thanks for reporting this! #131 fixes this.

**Comment by nklamann** [comment]
I have to thank you for the prompt fixing. The documentation is much clearer now !
