### ISSUE TITLE
Support for OVH, freeipa and Bind9 api/zones

### ISSUE THREAD

**Issue by mutech** [ansible-collections/community.dns#166]
##### SUMMARY
Support for OVH, FreeIPA and Bind9 zone files

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.dns.ovh, community.dns.zone_file, community.dns.freeipa

##### ADDITIONAL INFORMATION
This is not so much a feature request as an offer to implement it. However, I'm almost certainly not going to be able to maintain it once it's implemented. Would that be interesting to you (get the implementation and then maintain it?)

The reason why I'm opening an issue is that I would probably base my implementation heavier on dnspython than you did if I had to maintain it myself and implement only what I need myself. 

I could also probably do with some discussions about how to best structure parameters (all three of these probably require more configuration than a single API token) and how to go about interfacing FreeIPA and Bind9-Zone files.

On top of that I'm new to Ansible plugin development and would like to avoid the most rookie mistakes, so any advice would be most welcome.

**Comment by felixfontein** [comment]
@mutech thanks for your offer! Right now this collection has a set of very similar modules (using the same shared code, with different implementations for the DNS APIs itself) for two DNS providers. For every provider the set of modules follows a set of different use-cases. Having the same set of modules for every provider makes it very easy to migrate to another provider. (This is very different from the set of DNS modules in community.general and amazon.aws, where for every DNS provider you have a very different set of modules - often only one - that behave very differently. I would really like to avoid such a chaos for this collection.)

It would be great to have more DNS providers supported, but IMO the APIs for such modules should be very close. (To avoid the above-mentioned chaos.) For DNS providers with record based APIs (as opposed to record set based APIs) it would be best to use the existing framework. For record set based APIs, we do not have a framework so far.

**Comment by mutech** [comment]
I was looking into the hetzner implementation to get a feel how much work it would be to implement the OVH equivalent, and it looks like it's doable on my python/ansible level.  I liked your approach to have an abstraction layer on top of the base functionality, that's why I would like to use it. I will just probably not have the time to maintain it in the future as mentioned before (this is not my typical area of work).

For the bind9 plugin (basically aiming at editing zone files) I looked at dnspython. They have their own model which looks rather sophisticated. Out of curiosity, why did you not use that? It's a bit heavy, but on the flip side it has validation and looks to be well maintained. I though about adding a layer on top of dnspython's model to adapt it to yours (or in other words simulate an api that would basically be an action module getting the files from the server and writing it back). I'm not sure if this would be a bit too much to fit the functionality in your collection, but as you said, it would be nice to have a uniform interface to be able to switch (or even do things like migrating zones from one provider to another, something I had to do quite often lately).

FreeIPA should be straightforward - similar to OVH, with the only complication being that some records should probably not be editable directly (records associated with machine accounts can't just be updated - as far as I understand). Using the builtin DNS server of FreeIPA is a bit frowned upon, probably for this reason. But in my homelab setting it seems to make sense.

All three providers have some issues though. OVH does not use a single API token (they require a triplet). Bind9 would require an ansible connection setup (copy config) and a pathname to the zone file, freeipa probably gsapi or some other means of authentication. In all cases, the parameter interface would be rather heavy, so that I thought about a dict parameter named 'provider_config' or something like it.

By "record set based APIs" you mean something like f.e. grouping records by name/subDomain, like `{ name: some, type: A, values: [ 1.2.3.4, 1.2.3.5. ...] }`? Sorry I'm not deep into the topic and jargon.

**Comment by mutech** [comment]
One advantage of zone file support would be that that provider-independent functionality could be testable via that interface (with a bind9 running in a container). Though I have no experience at all with ansible module testing and I'm not looking forward to it :-)

**Comment by mutech** [comment]
@felixfontein Hi Felix! I started working on the OVH modules and faced a problem regarding dependencies (mostly owed to my rookie state). I wanted to use the OVH python API to avoid having to juggle with their quirky authentication mechanism and that hit the fan because module dependencies are not automatically installed on targets and I actually don't want them to be installed there either. I wondered why you guys implemented these actions as modules instead of using actions running on the controller, but assumed that there will be good reasons for it.

For what I'm doing (basically wanting to use the OVH api, really, really wanting to use dnspython for Bind9 and probably having to use actions for FreeIPA to have the kerberos ticket required to interface with IPA on the controller) I would really want to use actions. Before I start sinking tons of time into this, are there actually good reasons to use modules instead of actions that are going to take revenge on me? Would you want to accept a PR that uses actions and if yes, wouldn't it be better to refactor the modules to become actions for the existing modules?

**Comment by felixfontein** [comment]
> For the bind9 plugin (basically aiming at editing zone files) I looked at dnspython. They have their own model which looks rather sophisticated. Out of curiosity, why did you not use that?

Because it would be an extra dependency that users have to install before they can use the module.

> All three providers have some issues though. OVH does not use a single API token (they require a triplet). Bind9 would require an ansible connection setup (copy config) and a pathname to the zone file, freeipa probably gsapi or some other means of authentication. In all cases, the parameter interface would be rather heavy, so that I thought about a dict parameter named 'provider_config' or something like it.

I would use separate options instead of a dict. The hosttech modules also have three authentation options, where you either provide a token (for the newer JSON API) or username+password (for the SOAP API).

> By "record set based APIs" you mean something like f.e. grouping records by name/subDomain, like `{ name: some, type: A, values: [ 1.2.3.4, 1.2.3.5. ...] }`? Sorry I'm not deep into the topic and jargon.

A record set based API requires you to change all values for a name and type at the same time. A record based API manages the different values separately, so you have to 'manually' delete the values you don't need, modify existing entries, or add new values when needed. The Hetzner and Hosttech APIs are record based, while the Amazon Route53 API is record set based (IIRC).

> I wondered why you guys implemented these actions as modules instead of using actions running on the controller, but assumed that there will be good reasons for it.

Because it's more flexible. Modules can be run both on the controller (with `delegate_to: localhost`) and the target. In fact, most DNS modules are always run on the controller by users, there's no reason to send the DNS credentials to a remote target.

But there are some situations where the controller cannot reach the API directly and the DNS code needs to be run on a remote target. That would not be possible to do if we would have created action plugins.

(Also tooling like argspec handling etc. is a lot better for modules than for action plugins.)

> I would really want to use actions. Before I start sinking tons of time into this, are there actually good reasons to use modules instead of actions that are going to take revenge on me? Would you want to accept a PR that uses actions and if yes, wouldn't it be better to refactor the modules to become actions for the existing modules?

There is usually no good reason to create an action plugin instead of a module. Action plugins should only be done for very specific situations where some operations must **always** be run on the controller and it is **impossible** to do them on the remote (for example, for doing templating).

**Comment by mutech** [comment]
Hi @felixfontein 

Thanks for the clarification, that helped!

> I would use separate options instead of a dict. The hosttech modules also have three authentation options, where you either provide a token (for the newer JSON API) or username+password (for the SOAP API).

Okay, I'll stick to that scheme then.

> > I would really want to use actions. Before I start sinking tons of time into this, are there actually good reasons to use modules instead of actions that are going to take revenge on me? Would you want to accept a PR that uses actions and if yes, wouldn't it be better to refactor the modules to become actions for the existing modules?
> 
> There is usually no good reason to create an action plugin instead of a module. Action plugins should only be done for very specific situations where some operations must **always** be run on the controller and it is **impossible** to do them on the remote (for example, for doing templating).

> there's no reason to send the DNS credentials to a remote target.

I'm not sure that I would always be aware of this issue and delegate a DNS update to localhost in the context of deploying a service. Looking at how often I have to add a missing `become: yes` to my playbooks, I would not trust myself enough. Delegation also has a lot of quirks, depending on how the inventory is defined, that I personally try to avoid it whenever I can.

For the three providers I have three different reasons to want/need to use actions (in order from weakest to strongest):

- OVH: I would not want to maintain their imho weired authentication scheme and would rather just use their python API.
- Bind9 files: dnspython does all the work, so I think it's a non-brainer to use it for this part.
- FreeIPA: needs a Kerberos-Ticket for authentication (at least that's the usual way to authenticate) and that's best provided by in the session running ansible on the controller. 

Together with my aversion for installing python modules on targets, I would still like to implement them as actions. The lack of flexibility is a good counter argument, but I think reimplementing zone file parsers or having to manually authenticate to FreeIPA in playbooks seems to be worse than working around network blockades.

I think that if a public API is not reachable from the controller, that's an acceptable point of failure for a dns plugin (annoying as it would be for the person experiencing this particular limitation).

Would you be ok for me implementing these providers as actions (as in that not being a reason to reject a PR)?

Sorry if I'm stretching your patience with my lengthy comments and questions, I'm just trying to get it right and I'm still quite new to this stuff.

**Comment by mutech** [comment]
I realized that without using external dependencies, this is going to be 98% boiler plating and a lot of it mixed with copy & pasting external code into module_utils. Requiring dependencies on targets on the other hand is imho so bad that I really don't want to do it.

I'm going to close this issue, but thank you for your comments, they helped me learn quite a bit and also thank you for your work on this collection! 

This was a rather disappointing experience in regard to ansible extensions.
