### ISSUE TITLE
community.dns.lookup does not resolve ptr lookup request

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/community.dns#227]
##### SUMMARY

when using the lookup to resolve a ptr query it always returns an empty list

I tried 
```
- name: Debug 
  ansible.builtin.debug:
    var: lookup('community.dns.lookup', '10.0.0.20', server='10.0.0.10', type='PTR')
```
and i get an empty list.
I've tested the query with dig and I get an answer if I enter
```
dig +short @10.0.0.10 -x 10.0.0.20
myserver.example.com.
```

ansible-core version 2.16.12  (can't use latest on rocky 8)
comunity.dns version 3.0.6

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.dns.lookup

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below
ansible [core 2.16.12]
  config file = /home/rob/code/ictu/okd-infra/ansible.cfg
  configured module search path = ['/home/rob/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rob/code/ictu/okd-infra/.venv/lib64/python3.13/site-packages/ansible
  ansible collection location = /home/rob/code/ictu/okd-infra/collections:/home/rob/.ansible/collections
  executable location = /home/rob/code/ictu/okd-infra/.venv/bin/ansible
  python version = 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/home/rob/code/ictu/okd-infra/.venv/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/rob/code/ictu/okd-infra/ansible.cfg) = ['/home/rob/code/ictu/okd-infra/collections', '/home/rob/.ansible/collections']
CONFIG_FILE() = /home/rob/code/ictu/okd-infra/ansible.cfg
DEFAULT_FORKS(/home/rob/code/ictu/okd-infra/ansible.cfg) = 15
DEFAULT_HOST_LIST(/home/rob/code/ictu/okd-infra/ansible.cfg) = ['/home/rob/code/ictu/okd-infra/inventory']
EDITOR(env: EDITOR) = /usr/bin/vim
```

##### STEPS TO REPRODUCE

 test if record will resolv with dig command on host
```
dig +short @10.0.0.10 -x 10.0.0.20
```
test the lookup in a simple play

```yaml
- name: Debug 
  ansible.builtin.debug:
    var: lookup('community.dns.lookup', '10.0.0.20', server='10.0.0.10', type='PTR')
```

##### EXPECTED RESULTS

a string or a list of 2 or more elements

##### ACTUAL RESULTS

the lookup returns an empty list

```paste below
TASK [checks : Debug] ****************************
ok: [inventory_hostname] => {
    "lookup('community.dns.lookup', '10.0.0.20', server='10.0.0.10', type='PTR')": []
}
```

**Comment by felixfontein** [comment]
`10.0.0.20` is **not** a DNS name. It's an IP address. You want a reverse lookup, not a regular DNS lookup. This is not supported by the lookup.

**Comment by RobVerduijn** [comment]
> `10.0.0.20` is **not** a DNS name. It's an IP address. You want a reverse lookup, not a regular DNS lookup. This is not supported by the lookup.

ok so it's not a dns name.

I did the rtfm and the google exercise, but I can't seem to find a working example as to how to use community.dns lookup to query a PTR record from a dns server.

My bind dns server contains a PTR record in one of it's zone definitions.
And I wanted to validate the PTR record to ensure it is set to the correct value.

Could you please specify the propper syntax of doing this with a working example ?
ie something that I can copy and paste to the command line to see the result.

**Comment by felixfontein** [comment]
Right now community.dns does not offer any functionality for doing reverse lookups in a *simple* way.

What you can definitely do is doing a "manual" reverse lookup using https://en.wikipedia.org/wiki/Reverse_DNS_lookup#Implementation_details:
```
$ ansible localhost -m debug -a 'msg={{ lookup("community.dns.lookup", "4.4.8.8.in-addr.arpa.", type="PTR") }}'
[WARNING]: No inventory was parsed, only implicit localhost is available
localhost | SUCCESS => {
    "msg": "dns.google."
}
```
dig's `-x` parameter is a fancy way of taking its value (the IP address), rewriting it according to the rules described in https://en.wikipedia.org/wiki/Reverse_DNS_lookup#Implementation_details, and do a PTR lookup for the resulting DNS name (`20.0.0.10.in-addr.arpa.` in your example).

**Comment by RobVerduijn** [comment]
Thank you for the example.

An enhancement to community.dns that does this for you would be great.

This would be my current oneliner to test an ip
```bash
IP='8.8.4.4' ansible localhost -m debug -a 'msg={{ lookup("community.dns.lookup", ((lookup("ansible.builtin.env","IP") | ansible.builtin.split(".")) | reverse | join(".")) +".in-addr.arpa.", type="PTR") }}'
```

It doesn't look much better in a playbook

```
- name: Lookup test
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    my_ip: '8.8.4.4'
  tasks:
    - name: Lookup PTR record
      ansible.builtin.debug:
        msg: "{{ lookup('community.dns.lookup', (my_ip | ansible.builtin.split('.')) | reverse | join('.') + '.in-addr.arpa.', type='PTR') }}"
```
