### ISSUE TITLE
UX of _record modules

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.dns#29]
##### SUMMARY
Right now, the UX of the `hosttech_dns_record` (and future `hetzner_dns_record`) module isn't so great IMO. When I created the module originally, I was looking at the [route53](https://docs.ansible.com/ansible/latest/collections/community/aws/route53_module.html) module (now part of community.aws). It has some characteristics which I'm not very happy about, and some which are also different from [markuman.hetzner_dns.record](https://github.com/markuman/hetzner_dns/blob/main/plugins/modules/record.py#L55-L65).

###### Current problems and differences

In this issue I want to list the important differences (I'm ignoring that this module handles record sets, while the markuman.hetzner_dns.record module handles individual records):

1. `state` is required and must always be specified. (This is different in markuman.hetzner_dns.record and quite some other Ansible modules, though I personally prefer this, since it requires the user to be more explicit about what should happen.)

2. For most but some very explicit operations (namely creating a new record set which didn't exist before, or ensuring a record set has a specific value, or making sure a specific record set value is removed if not already absent), `overwrite: true` must be specified to avoid failing the module.

3. There are three ways to remove records: `state: absent` combined with `value: ...` and `overwrite: false` (here the exact value that is present must be specified); `state: absent` combined with `value: ...` (`value` must *always* be specified, any value will do here, also `[]`) and `overwrite: true`; or `state: present` combined with `value: []` and `overwrite: true`. The first method will fail if the record set has any other value, while the other two will always remove the record set (if it isn't already gone).

4. More differences to `markuman.hetzner_dns.record`: the hetzner_dns_record module uses `prefix` instead of `name` (thankfully tou don't have to provide `record` as in `route53` :) ) , and `zone` instead of `zone_name`.

###### Ways to proceed

1. About `state`, I think it's good to have `state` required. @markuman what do you think?

2. I'm currently thinking on switching the default of `overwrite` from `false` to `true`. While the functionality of `overwrite: false` is sometimes nice to have, in most cases I find it annoying.

3. I think `value` should only be required when `state: absent` if `overwrite` is `false` (to make sure only an explicit value is removed). Being able to remove with `state: present` and `value: []` is ok IMO, but forcing users to always provide `value` when `state: absent` is really annoying.

4. I think adding an alias `zone_name` of `zone` is good. For `name` vs. `prefix`, I'm not really happy about such a generic term as `name`; how about adding a deprecated alias `name` for `prefix` only for the `hetzner_dns_record` module?

@markuman what do you think?

Changing the default of `overwrite` would happen by deprecating its default now, with "removal" (i.e. switch to new default) in version 2.0.0. It might be a good idea to switch to 2.0.0 soon (so that if community.dns is included in Ansible 5, it will be version 2.x.y and not 1.z.w).

##### ISSUE TYPE
- UX Discussion

##### COMPONENT NAME
hosttech_dns_record
hetzner_dns_record

**Comment by markuman** [comment]
> 1. About state, I think it's good to have state required. @markuman what do you think?

I Agree.

> 2. For most but some very explicit operations (namely creating a new record set which didn't exist before, or ensuring a record set has a specific value, or making sure a specific record set value is removed if not already absent), overwrite: true must be specified to avoid failing the module.

I'm fine with that. I think most users will use `overwrite: true`. and when you need dns loadbalancing with multiple records, which are not set via `_records`, the user can simple turn `overwrite: false`.

> 3. ...
>  The first method will fail if the record set has any other 

In this case I would expect no fail. just a `not changed` task (_idempotent removed_).  
But in general I would agree here also.


> 4.I think adding an alias zone_name of zone is good. For name vs. prefix, I'm not really happy about such a generic term as name; how about adding a deprecated alias name for prefix only for the hetzner_dns_record module?

+1 for zone and zone_name  alias

In the past, there was an issue in my collection. where similiar parameter questions were discussed.  
https://github.com/markuman/hetzner_dns/issues/4#issuecomment-818865901  

| module | dns record name parameter |
| --- | --- |
| `community.general.gandi_livedns` | `record` |
| `community.general.netcup_dns ` | `record` _alias name_ |
| `community.general.dnsimple` | `record `|
| `community.aws.route53` | `record` |
| `markuman.hetzner_dns`| `name` |
| `community.dns` | `prefix` |

I think I've chosen `name`, because `name` was the parameter for that in the hetzner API.  
The question if, if community.dns should follow the maintstream and took/support the `record` parameter also?

> how about adding a deprecated alias name for prefix only for the hetzner_dns_record module?

I'm targeting with this suggestion just the switch from `markuman.hetzner_dns` to `community.dns`  
it would be very helpful if it's just working as a drop-in replacement for the first release. In that case I would just release 1.7.0 of markuman.hetzner_dns and added some deprecation messages that community.dns should be used as a drop-in replacement.    
When `name` is an alias will be just added temporary (_marked as deprecated_), I'm fine with it.

**Comment by felixfontein** [comment]
> > 3. ...
> >    The first method will fail if the record set has any other
> 
> In this case I would expect no fail. just a `not changed` task (_idempotent removed_).
> But in general I would agree here also.

I think it's hard to define the "correct" behavior, and this should probably not be a boolean toggle but offer a full range of options:
- `replace` (currently `overwrite: true`)
- `fail` (currently `overwrite: false`)
- `warn`
- `ignore`

You apparantly prefer `ingore`, I would probably prefer `fail` in these cases (I never had a need for them yet). If there's already another value in there which I don't expect, I want something else than just "not changed" (which I only expect if the value I want to set is already there).

> > 4.I think adding an alias zone_name of zone is good. For name vs. prefix, I'm not really happy about such a generic term as name; how about adding a deprecated alias name for prefix only for the hetzner_dns_record module?
> 
> +1 for zone and zone_name alias
> 
> In the past, there was an issue in my collection. where similiar parameter questions were discussed.
> [markuman/hetzner_dns#4 (comment)](https://github.com/markuman/hetzner_dns/issues/4#issuecomment-818865901)
> module 	dns record name parameter
> `community.general.gandi_livedns` 	`record`
> `community.general.netcup_dns ` 	`record` _alias name_
> `community.general.dnsimple` 	`record `
> `community.aws.route53` 	`record`
> `markuman.hetzner_dns` 	`name`
> `community.dns` 	`prefix`
> 
> I think I've chosen `name`, because `name` was the parameter for that in the hetzner API.
> The question if, if community.dns should follow the maintstream and took/support the `record` parameter also?

Well, the module already supports the `record` parameter, but in the sense of route53 (where you must specify the full DNS name, and not just the prefix), and not in the sense of gandi_livedns, netcup_dns and dnsimple (where you must specify the prefix). Which also means there is no real mainstream, and community.dns already does it better than the other modules by offering both options :)

> > how about adding a deprecated alias name for prefix only for the hetzner_dns_record module?
> 
> I'm targeting with this suggestion just the switch from `markuman.hetzner_dns` to `community.dns`
> it would be very helpful if it's just working as a drop-in replacement for the first release. In that case I would just release 1.7.0 of markuman.hetzner_dns and added some deprecation messages that community.dns should be used as a drop-in replacement.
> When `name` is an alias will be just added temporary (_marked as deprecated_), I'm fine with it.

Sounds good then.

There's a problem though: the hetzner_dns_record module is pretty different from your module, so there are a lot of cases where it simply cannot be used to replace it, since it works on record sets and not on single records. This might be a bigger problem.

(I guess I should have called `hosttech_dns_record` `hosttech_dns_record_set` instead...)

**Comment by felixfontein** [comment]
Hmm, how about the following:
1. Create a last 1.x.0 minor version without the Hetzner PR, create a stable-1 branch, then merge the Hetzner PR, and refactor as follows:
2. Rename `*_dns_record` to `*_dns_record_set`, `*_dns_records` to `*_dns_record_sets`; replace it's `overwrite` flag by an option with `choices` (see above);
3. Add new `*_dns_record` modules which allow to modify individual records (without the `purge` parameter or something like it: if you need something like that, use `*_dns_record_set` instead).
4. This will be a breaking change (since old uses of `hosttech_dns_record*` needs to be modified), so this will get released as 2.0.0 eventually (after everything is polished).

Then basically users of your module can use `hetzner_dns_record` as a drop-in replacement for `purge: false`, and `hetzner_dns_record_set` as a drop-in replacement for `purge: true`.

What do you think about that?

**Comment by markuman** [comment]
Sounds good to me :+1:

**Comment by felixfontein** [comment]
I called the new option `on_existing` with values `replace`, `keep_and_fail`, `keep_and_warn` and `keep` (see #31).

**Comment by felixfontein** [comment]
The aliases have been added in #32.

**Comment by felixfontein** [comment]
The record modules have been added in #33.

**Comment by felixfontein** [comment]
The inventory plugins have been added in #37.

**Comment by felixfontein** [comment]
Everything from this issue is now implemented (I think :) ).
