### ISSUE TITLE
Handling of TXT entries for Hetzner's API

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.dns#48]
##### SUMMARY
From https://github.com/ansible-collections/community.dns/pull/27#issuecomment-877849978 and https://github.com/ansible-collections/community.dns/pull/27#issuecomment-877854324:

While testing this, I noticed a problem with idempotency when using TXT records: Hetzner's API accepts unquoted values and reformats them with quotes (to conform to the 256 character limit, see https://datatracker.ietf.org/doc/html/rfc1035#section-3.3, https://datatracker.ietf.org/doc/html/rfc1035#section-3.3.14), and returns them in quoted form. The module right now does not know about this, which causes idempotency problems. For example when I try to set a DKIM entry
```
v=DKIM1; k=rsa; p=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw5AwkgAWIK9IANXXo1Pzhk2F3aYjTETQ9pJvIHnPhKS7vK3dBtaox0oU7o481/v3cHzgBVfsubDcNHbUPmvR84ouNXPowLbUkXwRIpSEZfUPuf6LBfFL1tFXBl7xtCRomr0VGAACHUK4L8mmWoP1Ah3iH54163oncG20JI8xfJjHfKAscVD3k3Ls3gU/2J33gptHCZunXlW1beFb/OiDl6ECGB2KhYwSWN/AIsO8VfVIRpCRswK1WcTgN3ZwoiLIktBEJicktlPB6HU8PhRl/9u0O3pkNB/pFMx0iViNEVEH4Sr4v4urLOqeE2LYo0TVPDn1wtzOwOICFFxtVYxY0zO/NtwcYDJJNbRVFSBKP1ePhf7uFo2HS8GamVdeyBi/+vRbcGZ1/QMTRR82aPNnyx6azCEXjdAcGPBV4pRPjUfbS1sZzhNiUEGYqGWypZtaLbJ2yBDOXfCLpaaf1VctqJ93KhONDLPnM2pREK48/fM0mn6x9uuCSJXo3FSW9xjnUXzj7cGxOvtdX2qnfTitiIiPIZNb4k6qbBbft1rI8oHYnt5+YUeVcrsSpoLL2QNAx9bavhv/hTO6Av/7Qofw/caGcSpx9kPGaxMjSBIpa32zrwRj/0qDVm7xgp1qkZayv54URd/nyqrNx0ZC8ZxS2mKLGWiL5bsOkNcEGe0lzeUCAwEAAQ==
```
Either this way or with double quotes, the API always returns the value as
```
"v=DKIM1; k=rsa; p=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw5AwkgAWIK9IANXXo1Pzhk2F3aYjTETQ9pJvIHnPhKS7vK3dBtaox0oU7o481/v3cHzgBVfsubDcNHbUPmvR84ouNXPowLbUkXwRIpSEZfUPuf6LBfFL1tFXBl7xtCRomr0VGAACHUK4L8mmWoP1Ah3iH54163oncG20JI8xfJjHfKAscVD3k3Ls3gU/2J33g" "ptHCZunXlW1beFb/OiDl6ECGB2KhYwSWN/AIsO8VfVIRpCRswK1WcTgN3ZwoiLIktBEJicktlPB6HU8PhRl/9u0O3pkNB/pFMx0iViNEVEH4Sr4v4urLOqeE2LYo0TVPDn1wtzOwOICFFxtVYxY0zO/NtwcYDJJNbRVFSBKP1ePhf7uFo2HS8GamVdeyBi/+vRbcGZ1/QMTRR82aPNnyx6azCEXjdAcGPBV4pRPjUfbS1sZzhNiUEGYqGWypZta" "LbJ2yBDOXfCLpaaf1VctqJ93KhONDLPnM2pREK48/fM0mn6x9uuCSJXo3FSW9xjnUXzj7cGxOvtdX2qnfTitiIiPIZNb4k6qbBbft1rI8oHYnt5+YUeVcrsSpoLL2QNAx9bavhv/hTO6Av/7Qofw/caGcSpx9kPGaxMjSBIpa32zrwRj/0qDVm7xgp1qkZayv54URd/nyqrNx0ZC8ZxS2mKLGWiL5bsOkNcEGe0lzeUCAwEAAQ==" 
```
(note the `" "`s in the middle, and the space after the trailing `"`). For handling this correctly, I think the module should strip quoting from the API result (and from the module input, in case someone passes in quoted TXT entries).

Another experience: when I set a short enough TXT entry (i.e. <= 256 bytes) without spaces, Hetzner's API keeps the quotes if I add them, and doesn't add them if I don't add them. So if I pass `test` without quotes it is returned without quotes, and if I pass `"test"` with quotes it is returned with quotes.

Maybe there should be an option which tells the module how to handle quotes in TXT entries? So that people who want to explicitly set the quotes the way they want can do it however they want, and others (probably essentially everyone) can just let the module take care of the quotes.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hetzner_dns_record
hetzner_dns_record_info
hetzner_dns_record_set
hetzner_dns_record_sets

**Comment by pgassmann** [comment]
I would keep the same behaviour as the UI.

To achive idempotency, the TXT record should be supplied in single quotes including the double quotes. 

```yaml
type: TXT
value: '"v=DKIM1; k=rsa; p=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw5AwkgAWIK9IANXXo1Pzhk2F3aYjTETQ9pJvIHnPhKS7vK3dBtaox0oU7o481/v3cHzgBVfsubDcNHbUPmvR84ouNXPowLbUkXwRIpSEZfUPuf6LBfFL1tFXBl7xtCRomr0VGAACHUK4L8mmWoP1Ah3iH54163oncG20JI8xfJjHfKAscVD3k3Ls3gU/2J33g" "ptHCZunXlW1beFb/OiDl6ECGB2KhYwSWN/AIsO8VfVIRpCRswK1WcTgN3ZwoiLIktBEJicktlPB6HU8PhRl/9u0O3pkNB/pFMx0iViNEVEH4Sr4v4urLOqeE2LYo0TVPDn1wtzOwOICFFxtVYxY0zO/NtwcYDJJNbRVFSBKP1ePhf7uFo2HS8GamVdeyBi/+vRbcGZ1/QMTRR82aPNnyx6azCEXjdAcGPBV4pRPjUfbS1sZzhNiUEGYqGWypZta" "LbJ2yBDOXfCLpaaf1VctqJ93KhONDLPnM2pREK48/fM0mn6x9uuCSJXo3FSW9xjnUXzj7cGxOvtdX2qnfTitiIiPIZNb4k6qbBbft1rI8oHYnt5+YUeVcrsSpoLL2QNAx9bavhv/hTO6Av/7Qofw/caGcSpx9kPGaxMjSBIpa32zrwRj/0qDVm7xgp1qkZayv54URd/nyqrNx0ZC8ZxS2mKLGWiL5bsOkNcEGe0lzeUCAwEAAQ=="'
```

perhaps the module could output a warning if the returned value is different from the input.

WARNING: the value of the record was reformatted by the API, to achieve idempotency, use : `'<return value>'`

Not sure if that is possible.

**Comment by felixfontein** [comment]
> I would keep the same behaviour as the UI.

What's the behavior of the UI?

> To achive idempotency, the TXT record should be supplied in single quotes including the double quotes.
> 
> ```yaml
> type: TXT
> value: '"v=DKIM1; k=rsa; p=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw5AwkgAWIK9IANXXo1Pzhk2F3aYjTETQ9pJvIHnPhKS7vK3dBtaox0oU7o481/v3cHzgBVfsubDcNHbUPmvR84ouNXPowLbUkXwRIpSEZfUPuf6LBfFL1tFXBl7xtCRomr0VGAACHUK4L8mmWoP1Ah3iH54163oncG20JI8xfJjHfKAscVD3k3Ls3gU/2J33g" "ptHCZunXlW1beFb/OiDl6ECGB2KhYwSWN/AIsO8VfVIRpCRswK1WcTgN3ZwoiLIktBEJicktlPB6HU8PhRl/9u0O3pkNB/pFMx0iViNEVEH4Sr4v4urLOqeE2LYo0TVPDn1wtzOwOICFFxtVYxY0zO/NtwcYDJJNbRVFSBKP1ePhf7uFo2HS8GamVdeyBi/+vRbcGZ1/QMTRR82aPNnyx6azCEXjdAcGPBV4pRPjUfbS1sZzhNiUEGYqGWypZta" "LbJ2yBDOXfCLpaaf1VctqJ93KhONDLPnM2pREK48/fM0mn6x9uuCSJXo3FSW9xjnUXzj7cGxOvtdX2qnfTitiIiPIZNb4k6qbBbft1rI8oHYnt5+YUeVcrsSpoLL2QNAx9bavhv/hTO6Av/7Qofw/caGcSpx9kPGaxMjSBIpa32zrwRj/0qDVm7xgp1qkZayv54URd/nyqrNx0ZC8ZxS2mKLGWiL5bsOkNcEGe0lzeUCAwEAAQ=="'
> ```

I disagree. Having the outer double quotes is ok, but the inner double quotes? That's forcing users to care about some obscure implementation detail of DNS that nobody should have to care about.

**Comment by pgassmann** [comment]
behaviour of the UI is the same as the API, it adds the quotes. and returns (displays) them, including the middle ones.

if the module would issue a warning every time you supply something that's returned differently and tell you what you need to supply to make it idempotent, I would welcome that.

> WARNING: the value of the record was reformatted by the API, to achieve idempotency, use : '<return value>'

in any other way you would need to have some clever quote parsing. There will certainly be cases where that logic makes something unintended. what if you have a value like `"["foo"="Bar" "key="value"]"` in a text record?

in the test zone, I have the following record (because of ansible string conversion)

`@	300	IN	TXT	"['" "v=spf1" "include:spf.protection.outlook.com" "include:spf.emailsignatures365.com" "~all" "', '" "google-site-verification=ztsNDgUhkjhlkhjlhjwG4I" "']" `

that's valid and is returned that way by dig.

**Comment by felixfontein** [comment]
I think it would be good if the modules allow to configure this behavior, since there are obviously different opinions on how the modules should behave :)

What do you think about the following API:
```.yaml
  txt_handling:
    description:
      - This option determines how the module will handle values for TXT records.
      - C(api) will pass the values as provided and return them as given by the API.
        Idempotency checks will simply compare strings without any normalization.
      - C(dns) will require and make sure that the values are quoted in double quotes (C("))
        if they contain spaces or are longer than 255 bytes, and use multiple space-delimited
        double quoted strings to handle values longer than 255 bytes.
      - C(normalized) will automatically normalize values returned by the API, and make
        sure that values are sent in the correct format to the API. This allows to ignore
        double quotes and the 255 bytes limit.
    type: str
    choices:
      - api
      - dns
      - normalized
    default: normalized
```
The value `api` does no transformations or validations; `dns` only accepts correctly formatted values; `normalized` allows the user to forget about double quotes and the 255 bytes limit.

**Comment by markuman** [comment]
> ```yaml
> type: TXT
> value: '"v=DKIM1; k=rsa; p=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw5AwkgAWIK9IANXXo1Pzhk2F3aYjTETQ9pJvIHnPhKS7vK3dBtaox0oU7o481/v3cHzgBVfsubDcNHbUPmvR84ouNXPowLbUkXwRIpSEZfUPuf6LBfFL1tFXBl7xtCRomr0VGAACHUK4L8mmWoP1Ah3iH54163oncG20JI8xfJjHfKAscVD3k3Ls3gU/2J33g" "ptHCZunXlW1beFb/OiDl6ECGB2KhYwSWN/AIsO8VfVIRpCRswK1WcTgN3ZwoiLIktBEJicktlPB6HU8PhRl/9u0O3pkNB/pFMx0iViNEVEH4Sr4v4urLOqeE2LYo0TVPDn1wtzOwOICFFxtVYxY0zO/NtwcYDJJNbRVFSBKP1ePhf7uFo2HS8GamVdeyBi/+vRbcGZ1/QMTRR82aPNnyx6azCEXjdAcGPBV4pRPjUfbS1sZzhNiUEGYqGWypZta" "LbJ2yBDOXfCLpaaf1VctqJ93KhONDLPnM2pREK48/fM0mn6x9uuCSJXo3FSW9xjnUXzj7cGxOvtdX2qnfTitiIiPIZNb4k6qbBbft1rI8oHYnt5+YUeVcrsSpoLL2QNAx9bavhv/hTO6Av/7Qofw/caGcSpx9kPGaxMjSBIpa32zrwRj/0qDVm7xgp1qkZayv54URd/nyqrNx0ZC8ZxS2mKLGWiL5bsOkNcEGe0lzeUCAwEAAQ=="'
> ```

imo most of the users are lazy and just hack away `value: some text` and not `value: '"some text"'`.   
they expect that ansible/the modules handle this magic without knowing much about api details/services/whatever.  

from my side :+1: for `normalized` mode as the default mode.  
the other options are nice to have for people that know what they are doing.  
the documentation should include those examples to demonstrate the differences.

**Comment by pgassmann** [comment]
The `dns` and normalized description are hard to understand. I still don't understand `dns` mode. Is that just input validation?

**Comment by felixfontein** [comment]
Yes, `dns` is essentially `api` with input validation. Not sure whether it's really necessary though.

About the `normalized` description, I'm also not happy with it, but right now I can't think of a better one (it's getting late for me). If you have a suggestion, please add it :)

**Comment by felixfontein** [comment]
(Looks like I also referenced the wrong issue in the PR...)

**Comment by felixfontein** [comment]
While working on #57 I noticed that while Hetzner's API does want `\"` and `\\` for `"` resp. `\`, it does not accept octal representation (`\123`), but instead wants unicode characters. These are returned in octal representation by the nameserver themselves (as expected), but the API returns with 500 Internal Server Error if you try to pass the octal representation to it. It does accept unicode and returns unicode. :shrug:

**Comment by felixfontein** [comment]
I have a first working implementation for this in #57. The documentation of the new option is now as follows, I hope it is better to understand. If not, please make suggestions on how to improve it :)
```.yaml
    txt_transformation:
        description:
            - Determines how TXT entry values are converted between the API and this module's
              input and output.
            - The value C(api) means that values are returned from this module as they are returned
              from the API, and pushed to the API as they have been passed to this module. For
              idempotency checks, the input string will be compared to the strings returned by the
              API.
            - The value C(normalized) automatically transforms values so that you can pass in unquoted
              values, and the module will return unquoted values. If you pass in quoted values, they
              will be double-quoted.
            - The value C(dns) automatically transforms values so that you must use quoting for values
              that contain spaces, characters such as quotation marks and backslashes, and that are
              longer than 255 bytes. It also makes sure to return values from the API in a normalized
              encoding.
            - The default value, C(normalized), ensures that you can work with values without having
              to care about how to correctly quote for DNS.
            - B(Note:) the conversion code assumes UTF-8 encoding for values. If you need another
              encoding use I(txt_transformation=api) and handle the encoding yourself.
        type: str
        choices:
            - api
            - dns
            - normalized
        default: normalized
```

**Comment by pgassmann** [comment]
@felixfontein thank you. When would you use the dns mode? Wouldn't it be less confusing to just drop this option?

for `api` add: 

The API might transform some entries the same way as the UI does. It might add quotes and split longer entries. If your input does not match the transformed value, the record(s) will always be reported as changed by this module.

**Comment by felixfontein** [comment]
@pgassmann you need that if you want to pass in values that are already quoted.

**Comment by felixfontein** [comment]
I adjusted the text as follows: https://github.com/ansible-collections/community.dns/pull/57/commits/7b33bc49c1e30221133fbe480d50d37230860431

**Comment by felixfontein** [comment]
How about renaming `normalized` to `unquoted` (or something like that)? And maybe `dns` to `quoted` or `dns-quoted`?

**Comment by markuman** [comment]
When changing `normalized` to `unquoted`, the `dns` value must become `quoted` and not `dns-quoted` imo.

I'm fine with that.

**Comment by felixfontein** [comment]
I've implemented the rename in 26e01715afbef2300189be7f6e5ffd3419c9ac35.

**Comment by felixfontein** [comment]
Any more comments on this? If not, I'll merge #57 and release another alpha version (2.0.0-a2) for testing.

**Comment by felixfontein** [comment]
@pgassmann @markuman thanks for your comments and suggestions!
