### ISSUE TITLE
Handle CNAME/SOA/... record matching differently than other records?

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.dns#49]
##### SUMMARY
Certain record types, such as CNAME and SOA, can only appear once for a given prefix.

Should the record and record set modules be aware of this?

1. The *_dns_record modules could always replace such a record instead of forcing the user to use the *_dns_record_set module to modify them.
2. The *_dns_record_set and *_dns_record_sets modules could error out before contacting the API when the user specifies more than one value for such a record set.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
*_dns_record
*_dns_record_set
*_dns_record_sets

**Comment by pgassmann** [comment]
In the Hetzner UI, the SOA record is not directly editable, only through zone file editing.
![image](https://user-images.githubusercontent.com/460192/127738518-7c9d5657-fbe9-41e6-9b87-8c00d4459b86.png)

The SOA record cannot be set idempotently, the timestamp is always modified by the api.

I would argue, that in most cases users would want to replace records for the same type and prefix. so most of the time they should use _dns_record_set. For that reason, I would even reject all types that cannot be additive. Don't support CNAME and SOA, even if the record does not yet exist, directly force the user to use _set. That could help prevent unintended additions instead of changes.

**Comment by felixfontein** [comment]
> In the Hetzner UI, the SOA record is not directly editable, only through zone file editing.
> ![image](https://user-images.githubusercontent.com/460192/127738518-7c9d5657-fbe9-41e6-9b87-8c00d4459b86.png)

The API allows to directly modify it.

> The SOA record cannot be set idempotently, the timestamp is always modified by the api.

Interestingly, the API returns the value sent to the API as a reply to the modifying request. On a subsequent GET it does return the value with the updated timestamp (which is a date), though.

> I would argue, that in most cases users would want to replace records for the same type and prefix. so most of the time they should use _dns_record_set. For that reason, I would even reject all types that cannot be additive. Don't support CNAME and SOA, even if the record does not yet exist, directly force the user to use _set. That could help prevent unintended additions instead of changes.

There are valid use-cases for the record module for SOA and CNAME as well, like adjusting the TTL, or for CNAME deleting a specific value (and not modifying any other values). I prefer not to stop the user from doing something valid that's compatible with the module's aim.

But preventing an invalid operation before the API is involved is something I think the module could do, so you would also find out in check mode that you are about to do something bad.

**Comment by pgassmann** [comment]
> There are valid use-cases for the record module for SOA and CNAME as well, like adjusting the TTL, or for CNAME deleting a specific value (and not modifying any other values). I prefer not to stop the user from doing something valid that's compatible with the module's aim.

These operations can just as well be done with the record_set module. That should be the advised default module unless you want to independently add individual values for the same prefix. 

I would add a warning to [the documentation of dns_record](https://ansible.fontein.de/collections/community/dns/hetzner_dns_record_module.html#ansible-collections-community-dns-hetzner-dns-record-module) like: 

WARNING this will add additional values for the same prefix (aka subdomain). Most of the time that's not what you intend. Use *_dns_record_set to replace the current value of a prefix.

**Comment by felixfontein** [comment]
I think it would be good if the modules allow to configure this behavior, since there are obviously different opinions on how the modules should behave :)

What do you think about the following API:
```.yaml
  txt_handling:
    description:
      - This option determines how the module will handle values for TXT records.
      - C(api) will pass the values as provided and return them as given by the API.
        Idempotency checks will simply compare strings without any normalization.
      - C(dns) will require and make sure that the values are quoted in double quotes (C("))
        if they contain spaces or are longer than 255 bytes, and use multiple space-delimited
        double quoted strings to handle values longer than 255 bytes.
      - C(normalized) will automatically normalize values returned by the API, and make
        sure that values are sent in the correct format to the API. This allows to ignore
        double quotes and the 255 bytes limit.
    type: str
    choices:
      - api
      - dns
      - normalized
    default: normalized
```
The value `api` does no transformations or validations; `dns` only accepts correctly formatted values; `normalized` allows the user to forget about double quotes and the 255 bytes limit.

**Comment by felixfontein** [comment]
I created #55 to add such a warning.
