### ISSUE TITLE
Allow default TTLs

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.dns#50]
##### SUMMARY
For provides which allow this (namely: Hetzner), allow that records do not have a TTL specified (i.e. allow the value `None` internally).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hetzner_dns_record
hetzner_dns_record_info
hetzner_dns_record_set
hetzner_dns_record_sets

**Comment by markuman** [comment]
Just a note for history.  
When TTL is not requested, hetzner uses the zones default TTL but return `TTL: None` for the record. That make immutable behavior difficult in some cases.

**Comment by felixfontein** [comment]
resolved_by_pr #52
